# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: local
  hooks:
  - id: update-pip-requirements
    name: Update pip requirements
    description: This hook exports requires from Poetry to pip requirement
    entry: scripts/update-pip-requirements.sh
    language: script
    always_run: true
    stages: [post-commit]
