version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  build:
    executor:
      python/default:
        tag: 3.8.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Test
          command: poetry run pytest --version
workflows:
  main:
    jobs:
      - build
