# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_scenarios[started_game.json] 1'] = '{"type": "started_game", "user": "anna", "payload": {}, "to_state": {"attackers": ["anna"], "defender": "vasyl", "durak": null, "hands": {"anna": ["7H", "6H", "KH", "QD", "6D", "KD"], "vasyl": ["9H", "7S", "AD", "10C", "KC", "9S"], "igor": ["JH", "8S", "6C", "QH", "QC", "8D"], "grusha": ["QS", "9C", "AC", "9D", "AH", "AS"]}, "legal_attacks": {"cards": ["6D", "6H", "7H", "KD", "KH", "QD"], "limit": 6}, "legal_defenses": {}, "legal_passes": {"cards": [], "limit": 6}, "table": [], "pass_count": 0, "players": ["anna", "vasyl", "igor", "grusha"], "trump_suit": "diamonds", "winners": [], "yielded": [], "lowest_rank": "6", "attack_limit": 100, "with_passing": true, "collector": null, "cards_left": 12, "drawn_cards": ["10C", "6C", "6D", "6H", "7H", "7S", "8D", "8S", "9C", "9D", "9H", "9S", "AC", "AD", "AH", "AS", "JH", "KC", "KD", "KH", "QC", "QD", "QH", "QS", "anna", "grusha", "igor", "vasyl"], "seed": 0.4}}'

snapshots['test_scenarios[passed_with_last_card.json] 1'] = '{"type": "passed_with_many", "user": "anna", "payload": {"cards": ["10H"]}, "to_state": {"attackers": ["igor", "grusha"], "defender": "vasyl", "durak": null, "hands": {"anna": [null], "vasyl": ["AH", "10C"], "igor": ["9S", "QC"], "grusha": ["QS", null, "KH"]}, "legal_attacks": {"cards": [], "limit": 0}, "legal_defenses": {"10D": ["AH"], "10H": ["AH"]}, "legal_passes": {"cards": ["10C"], "limit": 0}, "table": [["10D"], ["10H"]], "pass_count": 1, "players": ["anna", "vasyl", "igor", "grusha"], "trump_suit": "hearts", "winners": [], "yielded": [], "lowest_rank": "6", "attack_limit": 100, "with_passing": true, "collector": null, "cards_left": 36, "drawn_cards": ["anna", "grusha", "igor", "vasyl"], "seed": 0.4}}'

snapshots['test_scenarios[defend_successfully_after_attack_plays_last_card.json] 1'] = '{"type": "yielded_attack", "user": "igor", "payload": {}, "to_state": {"attackers": ["anna"], "defender": "vasyl", "durak": null, "hands": {"anna": ["KS", "JD", "9H", "7S", "AD", "10C"], "vasyl": ["JC", "QS", "8C", "QH", "6H", "KC"], "igor": ["9S", "QD", "6S", "6D", "JS", "9S"], "grusha": ["7H", "6H", "KH", "QD", "6D", "KD"]}, "legal_attacks": {"cards": ["10C", "7S", "9H", "AD", "JD", "KS"], "limit": 6}, "legal_defenses": {}, "legal_passes": {"cards": [], "limit": 6}, "table": [], "pass_count": 0, "players": ["anna", "vasyl", "igor", "grusha"], "trump_suit": "spades", "winners": [], "yielded": [], "lowest_rank": "6", "attack_limit": 100, "with_passing": true, "collector": null, "cards_left": 24, "drawn_cards": ["10C", "6D", "6H", "7H", "7S", "9H", "9S", "AD", "KC", "KD", "KH", "QD", "anna", "grusha", "igor", "vasyl"], "seed": 0.4}}'

snapshots['test_scenarios[collect_rotates_properly.json] 1'] = '{"type": "yielded_attack", "user": "anna", "payload": {}, "to_state": {"attackers": ["igor"], "defender": "grusha", "durak": null, "hands": {"igor": ["9S", "6S", "6D", "JD", "QD", "JC", "JS", "QH", "QS"], "grusha": ["10C", "KC", "9S", "JH", "8S", "6C"], "anna": ["7H", "6H", "KH", "QD", "6D", "KD"], "vasyl": ["8C", "6H", "KS", "9H", "7S", "AD"]}, "legal_attacks": {"cards": ["6D", "6S", "9S", "JC", "JD", "JS", "QD", "QH", "QS"], "limit": 6}, "legal_defenses": {}, "legal_passes": {"cards": [], "limit": 6}, "table": [], "pass_count": 0, "players": ["igor", "grusha", "anna", "vasyl"], "trump_suit": "spades", "winners": [], "yielded": [], "lowest_rank": "6", "attack_limit": 100, "with_passing": true, "collector": null, "cards_left": 21, "drawn_cards": ["10C", "6C", "6D", "6H", "7H", "7S", "8S", "9H", "9S", "AD", "JH", "KC", "KD", "KH", "QD", "anna", "grusha", "igor", "vasyl"], "seed": 0.4}}'

snapshots['test_scenarios[yielding_when_defender_wins.json] 1'] = '{"type": "yielded_attack", "payload": {}, "user": "grusha", "to_state": {"attackers": ["anna"], "defender": "vasyl", "durak": null, "hands": {"anna": ["9H", "7S", "AD", "10C", "KC", "9S"], "vasyl": ["AC", "8H", "10D", "AS", "9C", "9H", "QD", "9S"], "igor": ["KC", "6D", "7H", "6H", "KH", "QD"], "grusha": ["KH", "AD", "KD", "JH", "6D", "KD"]}, "legal_attacks": {"cards": ["10C", "7S", "9H", "9S", "AD", "KC"], "limit": 8}, "legal_defenses": {}, "legal_passes": {"cards": [], "limit": 6}, "table": [], "pass_count": 0, "players": ["anna", "vasyl", "igor", "grusha"], "trump_suit": "diamonds", "winners": [], "yielded": [], "lowest_rank": "6", "attack_limit": 100, "with_passing": true, "collector": null, "cards_left": 24, "drawn_cards": ["10C", "6D", "6H", "7H", "7S", "9H", "9S", "AD", "KC", "KD", "KH", "QD", "anna", "grusha", "igor", "vasyl"], "seed": 0.4}}'

snapshots['test_scenarios[cannot_attack_with_unmatched_rank.json] 1'] = '{"type": "attacked_with_many", "payload": {"cards": ["KD", "6D"]}, "user": "cyril", "to_state": {"seed": 0.4, "durak": null, "hands": {"john": ["KC", "KH", "QC", "JS", "6S", "7C"], "cyril": ["QH", "6C", "JC", "6D", "7D", "7H", "JH", "7S", "AS", "JD", "KD", "AH"], "kevin": ["AC", "AD", "KS", "QD", "6H", "QS"], "maxim": ["10H", "8S", "9S", "8C", "9C", "8H", "9H", "8D", "10D", "9D", "10C", "10S"]}, "table": [], "players": ["cyril", "kevin", "john", "maxim"], "winners": [], "yielded": [], "defender": "kevin", "attackers": ["cyril"], "collector": null, "draw_pile": [], "pass_count": 0, "trump_suit": "clubs", "lowest_rank": "6", "attack_limit": 6, "legal_passes": {"cards": [], "limit": 6}, "with_passing": true, "legal_attacks": {"cards": ["QH", "7D", "JH", "6D", "JC", "AS", "JD", "7H", "7S", "AH", "6C", "KD"], "limit": 6}, "legal_defenses": {}}, "no_display": true}'
